# Brewfile for Amiberry-Lite macOS development builds
brew "cmake"
brew "ninja"
brew "sdl2"
brew "sdl2_image"
brew "sdl2_ttf"
brew "flac"
brew "mpg123"
brew "libpng"
brew "zstd"
brew "libserialport"
brew "portmidi"
brew "enet"
brew "libmpeg2"
brew "dylibbundler"
